// 瘋殺假資料
import {
  onsaleDaajcn1900JERMI,
  onsaleDaao4k1900I5MBQ,
  onsaleDbabgwA900C2JED,
  onsaleDbaehb1900I6JGX,
  onsaleDbat8bA83578799,
  onsaleDbbc1eA9007PF9Y,
  onsaleDbbj071900F2VXM,
  onsaleDbcrl8A900JFT6Y,
  onsaleDbcz4qA900JD56O,
  onsaleDcakhpA900HEQ4H,
  onsaleDcbf01A900IUNKQ,
  onsaleDeawn3A900J1ZT9,
  onsaleDebv7oA900IOXYG,
  onsaleDebwa9A900GC92D,
  onsaleDgadkxA900JB6K8,
  onsaleDhas87A900J03M8,
  onsaleDidi2wA900ANP7Y,
  onsaleDmadfeA900HLJTD,
  onsaleDmaxb4A900J3TQO,
  onsaleDmaz1gA900FSV0J,
  onsaleDmba2yA900FVOQD,
  onsaleDmbl1cA900JA04J,
  onsaleDmbq0oA900GYMML,
  onsaleDmbq0vA900IGNT1,
  onsaleDpae6z1900J5B9T,
  onsaleDqbe2m1900JDO0N,
  onsaleDqcbdeA900IT5FG,
  onsaleDradky1900J5DJ6,
  onsaleDsabajA900JEGIH,
  onsaleDsabkbA900ITEBX,
  onsaleDsabrhA900JDPCH,
  onsaleDsao8sA900IUHYW,
  onsaleDyafm9A900ISBWO,
  onsaleDyaq9d1900J2XSA,
  onsaleDyawdjA900JF93O,
  onsaleDyba0xA900JBRC1,
} from '../assets/layout/index.js';

export const mockOnsaleData = [
  {
    products: [
      {
        id: 'DcakhpA900HEQ4H',
        url: '',
        productName: 'Ergohuman 特仕版 2.0人體工學椅',
        productTitle: '登記送512P幣',
        marketPrice: '16500',
        discountPrice: '9999',
        imgSrc: onsaleDcakhpA900HEQ4H,
        imgTitle: '',
        onsaleTime: '10:00:00',
        onsaleSticker: [
          {
            title: '刷台新卡',
            text: '最高享88折優惠',
            isEnabled: true,
          },
          {
            title: '下單送',
            text: '專屬配件套件組',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Dcbf01A900IUNKQ',
        url: '',
        productName: '雷蛇 Viper V3 PRO 毒蝰超輕量無線滑鼠',
        productTitle: '滿額送限量地墊',
        marketPrice: '4990',
        discountPrice: '3988',
        imgSrc: onsaleDcbf01A900IUNKQ,
        imgTitle: '',
        onsaleTime: '10:00:00',
        onsaleSticker: [],
      },
      {
        id: 'DsabajA900JEGIH',
        url: '',
        productName: 'ACER X32 X2 OLED 32型 4K電競螢幕',
        productTitle: '領券限量再折1000',
        marketPrice: '26999',
        discountPrice: '18999',
        imgSrc: onsaleDsabajA900JEGIH,
        imgTitle: '',
        onsaleTime: '10:00:00',
        onsaleSticker: [
          {
            title: '滿額登記',
            text: '送P幣高額回饋',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'DsabkbA900ITEBX',
        url: '',
        productName: 'ASUS ROG Strix XG27UCG 27型 4K電競螢幕',
        productTitle: '限時搶券折1000',
        marketPrice: '14888',
        discountPrice: '8988',
        imgSrc: onsaleDsabkbA900ITEBX,
        imgTitle: '',
        onsaleTime: '10:00:00',
        onsaleSticker: [
          {
            title: '會員專屬',
            text: '加碼現折500元',
            isEnabled: true,
          },
          {
            title: '分期零利率',
            text: '最高可分12期',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Dmaxb4A900J3TQO',
        url: '',
        productName: '石頭科技F25 Ultra吸拖洗地機',
        productTitle: '登記送1212P',
        marketPrice: '39900',
        discountPrice: '17912',
        imgSrc: onsaleDmaxb4A900J3TQO,
        imgTitle: '',
        onsaleTime: '15:00:00',
        onsaleSticker: [],
      },
      {
        id: 'Dyafm9A900ISBWO',
        url: '',
        productName: 'SHOWHAN N54強磁真空吸附360度旋轉支架',
        productTitle: '三軸折疊快速收納',
        marketPrice: '590',
        discountPrice: '299',
        imgSrc: onsaleDyafm9A900ISBWO,
        imgTitle: '',
        onsaleTime: '15:00:00',
        onsaleSticker: [
          {
            title: '買就送',
            text: '專屬收納袋好禮',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Dbbc1eA9007PF9Y',
        url: '',
        productName: '善存男性綜合維他命120錠',
        productTitle: '下單送7-11咖啡券',
        marketPrice: '910',
        discountPrice: '773',
        imgSrc: onsaleDbbc1eA9007PF9Y,
        imgTitle: '',
        onsaleTime: '15:00:00',
        onsaleSticker: [
          {
            title: '刷卡優惠',
            text: '滿千折百超划算',
            isEnabled: true,
          },
          {
            title: '加碼送',
            text: '咖啡券2張好禮',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Dyaq9d1900J2XSA',
        url: '',
        productName: 'PHILIPS 耳罩式耳機+真無線藍牙耳機組',
        productTitle: '現省$2410',
        marketPrice: '4000',
        discountPrice: '1590',
        imgSrc: onsaleDyaq9d1900J2XSA,
        imgTitle: '',
        onsaleTime: '15:00:00',
        onsaleSticker: [],
      },
      {
        id: 'Dmbq0vA900IGNT1',
        url: '',
        productName: '海爾 17.5公升一級能效除濕機',
        productTitle: '貨物稅減免$1200',
        marketPrice: '7980',
        discountPrice: '5911',
        imgSrc: onsaleDmbq0vA900IGNT1,
        imgTitle: '',
        onsaleTime: '21:00:00',
        onsaleSticker: [
          {
            title: '節能補助',
            text: '貨物稅減1200元',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Dqbe2m1900JDO0N',
        url: '',
        productName: 'Glolux 延長線1.5M 2入組',
        productTitle: '限量破盤',
        marketPrice: '899',
        discountPrice: '599',
        imgSrc: onsaleDqbe2m1900JDO0N,
        imgTitle: '',
        onsaleTime: '21:00:00',
        onsaleSticker: [
          {
            title: '限時特惠',
            text: '第2件享5折優惠',
            isEnabled: true,
          },
          {
            title: '滿額免運',
            text: '全館免運費優惠',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Dradky1900J5DJ6',
        url: '',
        productName: '華碩 TUF Gaming RTX 5060 8GB OC 顯示卡',
        productTitle: '限時下殺$1000',
        marketPrice: '12990',
        discountPrice: '11990',
        imgSrc: onsaleDradky1900J5DJ6,
        imgTitle: '',
        onsaleTime: '21:00:00',
        onsaleSticker: [],
      },
      {
        id: 'Didi2wA900ANP7Y',
        url: '',
        productName: '三花 吸汗透氣無痕肌紳士休閒襪6雙組',
        productTitle: '不易滑動 單雙99',
        marketPrice: '1680',
        discountPrice: '594',
        imgSrc: onsaleDidi2wA900ANP7Y,
        imgTitle: '',
        onsaleTime: '21:00:00',
        onsaleSticker: [
          {
            title: '超值組合',
            text: '單雙只要99元起',
            isEnabled: true,
          },
        ],
      },
    ],
  },
  {
    products: [
      {
        id: 'Dpae6z1900J5B9T',
        url: '',
        productName: 'OVO K9 4K智慧投影機',
        productTitle: '加碼小方塊投影機',
        marketPrice: '36999',
        discountPrice: '32999',
        imgSrc: onsaleDpae6z1900J5B9T,
        imgTitle: '',
        onsaleTime: '10:00:00',
        onsaleSticker: [
          {
            title: '加碼送',
            text: '小方塊投影機好禮',
            isEnabled: true,
          },
          {
            title: '分期付款',
            text: '0利率最高24期',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Debwa9A900GC92D',
        url: '',
        productName: '象印不鏽鋼一體式杯蓋真空燜燒杯',
        productTitle: '12/6一日驚喜價',
        marketPrice: '2000',
        discountPrice: '888',
        imgSrc: onsaleDebwa9A900GC92D,
        imgTitle: '',
        onsaleTime: '10:00:00',
        onsaleSticker: [],
      },
      {
        id: 'DsabrhA900JDPCH',
        url: '',
        productName: 'MSI MPG 321URXW QD-OLED 32型 4K電競螢幕',
        productTitle: '限量登記送1212P',
        marketPrice: '27900',
        discountPrice: '21900',
        imgSrc: onsaleDsabrhA900JDPCH,
        imgTitle: '',
        onsaleTime: '10:00:00',
        onsaleSticker: [
          {
            title: '登記送',
            text: '1212P幣回饋',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Dsao8sA900IUHYW',
        url: '',
        productName: '飛利浦6開6座延長線1.8M',
        productTitle: '加碼送10%P',
        marketPrice: '799',
        discountPrice: '499',
        imgSrc: onsaleDsao8sA900IUHYW,
        imgTitle: '',
        onsaleTime: '10:00:00',
        onsaleSticker: [],
      },
      {
        id: 'DyawdjA900JF93O',
        url: '',
        productName: 'POCO F8 Ultra 16GB/512GB',
        productTitle: '新機降千!抽P幣',
        marketPrice: '23999',
        discountPrice: '22999',
        imgSrc: onsaleDyawdjA900JF93O,
        imgTitle: '',
        onsaleTime: '15:00:00',
        onsaleSticker: [
          {
            title: '新機優惠',
            text: '現折降價千元',
            isEnabled: true,
          },
          {
            title: '抽獎活動',
            text: '最高抽5000P幣',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Dmbl1cA900JA04J',
        url: '',
        productName: '石頭科技 Qrevo Curv 2 Flow 掃拖機器人',
        productTitle: '最高登記送2200P',
        marketPrice: '59999',
        discountPrice: '19999',
        imgSrc: onsaleDmbl1cA900JA04J,
        imgTitle: '',
        onsaleTime: '15:00:00',
        onsaleSticker: [
          {
            title: '超殺優惠',
            text: '現省4萬元超值',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Dbcz4qA900JD56O',
        url: '',
        productName: '初品果高雄美濃雙色橙蜜小番茄禮盒3斤x2盒',
        productTitle: '初品果滿1212折80',
        marketPrice: '1400',
        discountPrice: '548',
        imgSrc: onsaleDbcz4qA900JD56O,
        imgTitle: '',
        onsaleTime: '15:00:00',
        onsaleSticker: [],
      },
      {
        id: 'Daao4k1900I5MBQ',
        url: '',
        productName: '幫寶適 極上守護 一級幫 拉拉褲 4箱',
        productTitle: '下單最高送532P',
        marketPrice: '5196',
        discountPrice: '3999',
        imgSrc: onsaleDaao4k1900I5MBQ,
        imgTitle: '',
        onsaleTime: '15:00:00',
        onsaleSticker: [
          {
            title: '下單送',
            text: '最高送532P幣',
            isEnabled: true,
          },
          {
            title: '箱購優惠',
            text: '買4箱省1197元',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Debv7oA900IOXYG',
        url: '',
        productName: 'Royal Canin 法國皇家室內成貓IN27 10KG',
        productTitle: '滿額登記送P幣',
        marketPrice: '3750',
        discountPrice: '2849',
        imgSrc: onsaleDebv7oA900IOXYG,
        imgTitle: '',
        onsaleTime: '21:00:00',
        onsaleSticker: [],
      },
      {
        id: 'Deawn3A900J1ZT9',
        url: '',
        productName: '康寧 藍寶石鑄造不沾深炒鍋30cm(含蓋)',
        productTitle: '下單送100P',
        marketPrice: '2580',
        discountPrice: '999',
        imgSrc: onsaleDeawn3A900J1ZT9,
        imgTitle: '',
        onsaleTime: '21:00:00',
        onsaleSticker: [
          {
            title: '限時搶購',
            text: '下殺只要39折',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Dbaehb1900I6JGX',
        url: '',
        productName: 'Airwaves口香糖 超涼薄荷 28g*20入',
        productTitle: '贈30P幣+好禮',
        marketPrice: '676',
        discountPrice: '499',
        imgSrc: onsaleDbaehb1900I6JGX,
        imgTitle: '',
        onsaleTime: '21:00:00',
        onsaleSticker: [
          {
            title: '買就送',
            text: '30P幣加贈好禮',
            isEnabled: true,
          },
          {
            title: '箱購更划算',
            text: '20入超值組合價',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Dyba0xA900JBRC1',
        url: '',
        productName: 'Choetech 氮化鎵140W PD快充器-附240W線',
        productTitle: '充手機筆電 2年保',
        marketPrice: '3100',
        discountPrice: '999',
        imgSrc: onsaleDyba0xA900JBRC1,
        imgTitle: '',
        onsaleTime: '21:00:00',
        onsaleSticker: [],
      },
    ],
  },
  {
    products: [
      {
        id: 'DqcbdeA900IT5FG',
        url: '',
        productName: '折疊款無段氣壓升降移動邊桌-2色可選',
        productTitle: '滿額登記送512P幣',
        marketPrice: '1999',
        discountPrice: '999',
        imgSrc: onsaleDqcbdeA900IT5FG,
        imgTitle: '',
        onsaleTime: '10:00:00',
        onsaleSticker: [
          {
            title: '破盤價',
            text: '直接下殺5折',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'DmadfeA900HLJTD',
        url: '',
        productName: '輝葉 震關健 2入組',
        productTitle: '下單贈1%P幣',
        marketPrice: '7960',
        discountPrice: '2612',
        imgSrc: onsaleDmadfeA900HLJTD,
        imgTitle: '',
        onsaleTime: '10:00:00',
        onsaleSticker: [
          {
            title: '組合優惠',
            text: '2入現省5348元',
            isEnabled: true,
          },
          {
            title: 'P幣回饋',
            text: '下單贈送1%P幣',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Dbat8bA83578799',
        url: '',
        productName: 'Casa 卡薩濾掛咖啡綜合組100入',
        productTitle: '下殺均入$6.5',
        marketPrice: '1380',
        discountPrice: '649',
        imgSrc: onsaleDbat8bA83578799,
        imgTitle: '',
        onsaleTime: '10:00:00',
        onsaleSticker: [],
      },
      {
        id: 'Dhas87A900J03M8',
        url: '',
        productName: 'ASUS 16吋R9-RTX5060電競筆電',
        productTitle: '直接送1000P幣',
        marketPrice: '46999',
        discountPrice: '41599',
        imgSrc: onsaleDhas87A900J03M8,
        imgTitle: '',
        onsaleTime: '10:00:00',
        onsaleSticker: [
          {
            title: '直接送',
            text: '直送1000P幣',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'DbabgwA900C2JED',
        url: '',
        productName: 'Red Bull 能量飲料 250ml (24罐/箱)',
        productTitle: '滿額登記送P幣',
        marketPrice: '1560',
        discountPrice: '1049',
        imgSrc: onsaleDbabgwA900C2JED,
        imgTitle: '',
        onsaleTime: '15:00:00',
        onsaleSticker: [
          {
            title: '整箱購',
            text: '單罐只要44元起',
            isEnabled: true,
          },
          {
            title: '滿額送',
            text: 'P幣高額回饋',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'DgadkxA900JB6K8',
        url: '',
        productName: 'PENTAX 17 底片相機 TKO標準版',
        productTitle: '狂降$2000',
        marketPrice: '17800',
        discountPrice: '15800',
        imgSrc: onsaleDgadkxA900JB6K8,
        imgTitle: '',
        onsaleTime: '15:00:00',
        onsaleSticker: [],
      },
      {
        id: 'Daajcn1900JERMI',
        url: '',
        productName: '上山採藥台灣茶系列洗髮/沐浴-任選4入',
        productTitle: '下單贈護唇膏',
        marketPrice: '1196',
        discountPrice: '499',
        imgSrc: onsaleDaajcn1900JERMI,
        imgTitle: '',
        onsaleTime: '15:00:00',
        onsaleSticker: [
          {
            title: '下單送',
            text: '護唇膏好禮贈送',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Dbbj071900F2VXM',
        url: '',
        productName: '克寧100%純生乳奶粉2.2kgx2罐',
        productTitle: '送雀巢焦糖瑪奇朵',
        marketPrice: '1740',
        discountPrice: '1212',
        imgSrc: onsaleDbbj071900F2VXM,
        imgTitle: '',
        onsaleTime: '15:00:00',
        onsaleSticker: [],
      },
      {
        id: 'Dmbq0oA900GYMML',
        url: '',
        productName: '威技 6L抗菌除濕機',
        productTitle: '貨物稅減免$500',
        marketPrice: '6990',
        discountPrice: '2999',
        imgSrc: onsaleDmbq0oA900GYMML,
        imgTitle: '',
        onsaleTime: '21:00:00',
        onsaleSticker: [
          {
            title: '節能家電',
            text: '貨物稅減免500元',
            isEnabled: true,
          },
          {
            title: '限時特價',
            text: '限時現省3991元',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Dmba2yA900FVOQD',
        url: '',
        productName: '歐姆龍HBF-371體重體脂計銀色',
        productTitle: '下單贈100P幣',
        marketPrice: '4080',
        discountPrice: '2812',
        imgSrc: onsaleDmba2yA900FVOQD,
        imgTitle: '',
        onsaleTime: '21:00:00',
        onsaleSticker: [
          {
            title: '贈送',
            text: '贈送100P幣',
            isEnabled: true,
          },
        ],
      },
      {
        id: 'Dbcrl8A900JFT6Y',
        url: '',
        productName: '星巴克中杯雙果果汁星冰樂',
        productTitle: '即買即用全台通用',
        marketPrice: '125',
        discountPrice: '99',
        imgSrc: onsaleDbcrl8A900JFT6Y,
        imgTitle: '',
        onsaleTime: '21:00:00',
        onsaleSticker: [],
      },
      {
        id: 'Dmaz1gA900FSV0J',
        url: '',
        productName: '北方 陶瓷遙控電暖器',
        productTitle: '節能模式自動調溫',
        marketPrice: '3280',
        discountPrice: '2682',
        imgSrc: onsaleDmaz1gA900FSV0J,
        imgTitle: '',
        onsaleTime: '21:00:00',
        onsaleSticker: [
          {
            title: '冬季必備',
            text: '節能省電超安心',
            isEnabled: true,
          },
        ],
      },
    ],
  },
];
